import axios from 'axios';
import { getCredentials } from '../utils/config.js';

export class AiService {
    constructor() { }

    async generate(prompt) {
        const { aiKey, aiProvider, aiEnabled } = getCredentials();

        if (!aiEnabled) {
            throw new Error('AI features are disabled. Run "jira config ai enable" to enable.');
        }

        if (!aiKey) {
            throw new Error('AI API Key not configured. Run "jira config ai enable" or "jira config setup".');
        }

        const provider = aiProvider || 'openai';

        switch (provider) {
            case 'openai':
                return this.callOpenAI(aiKey, prompt);
            case 'gemini':
                return this.callGemini(aiKey, prompt);
            case 'anthropic':
                return this.callAnthropic(aiKey, prompt);
            default:
                throw new Error(`Unsupported AI Provider: ${provider}. Supported: openai, gemini, anthropic`);
        }
    }

    async callOpenAI(key, prompt) {
        try {
            const response = await axios.post('https://api.openai.com/v1/chat/completions', {
                model: 'gpt-4o',
                messages: [{ role: 'user', content: prompt }],
                temperature: 0.7
            }, {
                headers: { 'Authorization': `Bearer ${key}` }
            });
            return response.data.choices[0].message.content;
        } catch (e) {
            throw new Error(`OpenAI API Error: ${e.response?.data?.error?.message || e.message}`);
        }
    }

    async callGemini(key, prompt) {
        try {
            // Gemini REST API — uses generativelanguage.googleapis.com
            const model = 'gemini-2.0-flash';
            const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${key}`;

            const response = await axios.post(url, {
                contents: [{
                    parts: [{ text: prompt }]
                }],
                generationConfig: {
                    temperature: 0.7,
                    maxOutputTokens: 2048
                }
            }, {
                headers: { 'Content-Type': 'application/json' }
            });

            const candidates = response.data.candidates;
            if (!candidates || candidates.length === 0) {
                throw new Error('No response generated by Gemini.');
            }

            return candidates[0].content.parts.map(p => p.text).join('');
        } catch (e) {
            if (e.response?.data?.error) {
                throw new Error(`Gemini API Error: ${e.response.data.error.message}`);
            }
            throw new Error(`Gemini API Error: ${e.message}`);
        }
    }

    async callAnthropic(key, prompt) {
        try {
            // Anthropic Messages API
            const response = await axios.post('https://api.anthropic.com/v1/messages', {
                model: 'claude-sonnet-4-20250514',
                max_tokens: 2048,
                messages: [{ role: 'user', content: prompt }]
            }, {
                headers: {
                    'x-api-key': key,
                    'anthropic-version': '2023-06-01',
                    'Content-Type': 'application/json'
                }
            });

            return response.data.content
                .filter(block => block.type === 'text')
                .map(block => block.text)
                .join('');
        } catch (e) {
            if (e.response?.data?.error) {
                throw new Error(`Anthropic API Error: ${e.response.data.error.message}`);
            }
            throw new Error(`Anthropic API Error: ${e.message}`);
        }
    }
}

export const aiService = new AiService();
